/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as AuthenticatedIndexRouteImport } from './routes/_authenticated/index'
import { Route as AuthenticatedVendasRouteImport } from './routes/_authenticated/vendas'
import { Route as AuthenticatedInsightsRouteImport } from './routes/_authenticated/insights'
import { Route as AuthenticatedGerentesRouteImport } from './routes/_authenticated/gerentes'
import { Route as AuthenticatedFinanceiroRouteImport } from './routes/_authenticated/financeiro'
import { Route as AuthenticatedEmpreendimentosRouteImport } from './routes/_authenticated/empreendimentos'
import { Route as AuthenticatedCorretoresRouteImport } from './routes/_authenticated/corretores'
import { Route as AuthenticatedComissoesRouteImport } from './routes/_authenticated/comissoes'
import { Route as AuthenticatedAprovacoesRouteImport } from './routes/_authenticated/aprovacoes'
import { Route as AuthenticatedAgendamentosRouteImport } from './routes/_authenticated/agendamentos'
import { Route as AuthenticatedAdminUsuariosRouteImport } from './routes/_authenticated/admin/usuarios'
import { Route as AuthenticatedAdminIntegracaoRouteImport } from './routes/_authenticated/admin/integracao'
import { Route as ApiPublicHooksCleanupNfDriveRouteImport } from './routes/api/public/hooks/cleanup-nf-drive'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedIndexRoute = AuthenticatedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedVendasRoute = AuthenticatedVendasRouteImport.update({
  id: '/vendas',
  path: '/vendas',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedInsightsRoute = AuthenticatedInsightsRouteImport.update({
  id: '/insights',
  path: '/insights',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedGerentesRoute = AuthenticatedGerentesRouteImport.update({
  id: '/gerentes',
  path: '/gerentes',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedFinanceiroRoute = AuthenticatedFinanceiroRouteImport.update({
  id: '/financeiro',
  path: '/financeiro',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedEmpreendimentosRoute =
  AuthenticatedEmpreendimentosRouteImport.update({
    id: '/empreendimentos',
    path: '/empreendimentos',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedCorretoresRoute = AuthenticatedCorretoresRouteImport.update({
  id: '/corretores',
  path: '/corretores',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedComissoesRoute = AuthenticatedComissoesRouteImport.update({
  id: '/comissoes',
  path: '/comissoes',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAprovacoesRoute = AuthenticatedAprovacoesRouteImport.update({
  id: '/aprovacoes',
  path: '/aprovacoes',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAgendamentosRoute =
  AuthenticatedAgendamentosRouteImport.update({
    id: '/agendamentos',
    path: '/agendamentos',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAdminUsuariosRoute =
  AuthenticatedAdminUsuariosRouteImport.update({
    id: '/admin/usuarios',
    path: '/admin/usuarios',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAdminIntegracaoRoute =
  AuthenticatedAdminIntegracaoRouteImport.update({
    id: '/admin/integracao',
    path: '/admin/integracao',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const ApiPublicHooksCleanupNfDriveRoute =
  ApiPublicHooksCleanupNfDriveRouteImport.update({
    id: '/api/public/hooks/cleanup-nf-drive',
    path: '/api/public/hooks/cleanup-nf-drive',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthenticatedIndexRoute
  '/login': typeof LoginRoute
  '/agendamentos': typeof AuthenticatedAgendamentosRoute
  '/aprovacoes': typeof AuthenticatedAprovacoesRoute
  '/comissoes': typeof AuthenticatedComissoesRoute
  '/corretores': typeof AuthenticatedCorretoresRoute
  '/empreendimentos': typeof AuthenticatedEmpreendimentosRoute
  '/financeiro': typeof AuthenticatedFinanceiroRoute
  '/gerentes': typeof AuthenticatedGerentesRoute
  '/insights': typeof AuthenticatedInsightsRoute
  '/vendas': typeof AuthenticatedVendasRoute
  '/admin/integracao': typeof AuthenticatedAdminIntegracaoRoute
  '/admin/usuarios': typeof AuthenticatedAdminUsuariosRoute
  '/api/public/hooks/cleanup-nf-drive': typeof ApiPublicHooksCleanupNfDriveRoute
}
export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/agendamentos': typeof AuthenticatedAgendamentosRoute
  '/aprovacoes': typeof AuthenticatedAprovacoesRoute
  '/comissoes': typeof AuthenticatedComissoesRoute
  '/corretores': typeof AuthenticatedCorretoresRoute
  '/empreendimentos': typeof AuthenticatedEmpreendimentosRoute
  '/financeiro': typeof AuthenticatedFinanceiroRoute
  '/gerentes': typeof AuthenticatedGerentesRoute
  '/insights': typeof AuthenticatedInsightsRoute
  '/vendas': typeof AuthenticatedVendasRoute
  '/': typeof AuthenticatedIndexRoute
  '/admin/integracao': typeof AuthenticatedAdminIntegracaoRoute
  '/admin/usuarios': typeof AuthenticatedAdminUsuariosRoute
  '/api/public/hooks/cleanup-nf-drive': typeof ApiPublicHooksCleanupNfDriveRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/login': typeof LoginRoute
  '/_authenticated/agendamentos': typeof AuthenticatedAgendamentosRoute
  '/_authenticated/aprovacoes': typeof AuthenticatedAprovacoesRoute
  '/_authenticated/comissoes': typeof AuthenticatedComissoesRoute
  '/_authenticated/corretores': typeof AuthenticatedCorretoresRoute
  '/_authenticated/empreendimentos': typeof AuthenticatedEmpreendimentosRoute
  '/_authenticated/financeiro': typeof AuthenticatedFinanceiroRoute
  '/_authenticated/gerentes': typeof AuthenticatedGerentesRoute
  '/_authenticated/insights': typeof AuthenticatedInsightsRoute
  '/_authenticated/vendas': typeof AuthenticatedVendasRoute
  '/_authenticated/': typeof AuthenticatedIndexRoute
  '/_authenticated/admin/integracao': typeof AuthenticatedAdminIntegracaoRoute
  '/_authenticated/admin/usuarios': typeof AuthenticatedAdminUsuariosRoute
  '/api/public/hooks/cleanup-nf-drive': typeof ApiPublicHooksCleanupNfDriveRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/agendamentos'
    | '/aprovacoes'
    | '/comissoes'
    | '/corretores'
    | '/empreendimentos'
    | '/financeiro'
    | '/gerentes'
    | '/insights'
    | '/vendas'
    | '/admin/integracao'
    | '/admin/usuarios'
    | '/api/public/hooks/cleanup-nf-drive'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/agendamentos'
    | '/aprovacoes'
    | '/comissoes'
    | '/corretores'
    | '/empreendimentos'
    | '/financeiro'
    | '/gerentes'
    | '/insights'
    | '/vendas'
    | '/'
    | '/admin/integracao'
    | '/admin/usuarios'
    | '/api/public/hooks/cleanup-nf-drive'
  id:
    | '__root__'
    | '/_authenticated'
    | '/login'
    | '/_authenticated/agendamentos'
    | '/_authenticated/aprovacoes'
    | '/_authenticated/comissoes'
    | '/_authenticated/corretores'
    | '/_authenticated/empreendimentos'
    | '/_authenticated/financeiro'
    | '/_authenticated/gerentes'
    | '/_authenticated/insights'
    | '/_authenticated/vendas'
    | '/_authenticated/'
    | '/_authenticated/admin/integracao'
    | '/_authenticated/admin/usuarios'
    | '/api/public/hooks/cleanup-nf-drive'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  LoginRoute: typeof LoginRoute
  ApiPublicHooksCleanupNfDriveRoute: typeof ApiPublicHooksCleanupNfDriveRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/': {
      id: '/_authenticated/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/vendas': {
      id: '/_authenticated/vendas'
      path: '/vendas'
      fullPath: '/vendas'
      preLoaderRoute: typeof AuthenticatedVendasRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/insights': {
      id: '/_authenticated/insights'
      path: '/insights'
      fullPath: '/insights'
      preLoaderRoute: typeof AuthenticatedInsightsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/gerentes': {
      id: '/_authenticated/gerentes'
      path: '/gerentes'
      fullPath: '/gerentes'
      preLoaderRoute: typeof AuthenticatedGerentesRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/financeiro': {
      id: '/_authenticated/financeiro'
      path: '/financeiro'
      fullPath: '/financeiro'
      preLoaderRoute: typeof AuthenticatedFinanceiroRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/empreendimentos': {
      id: '/_authenticated/empreendimentos'
      path: '/empreendimentos'
      fullPath: '/empreendimentos'
      preLoaderRoute: typeof AuthenticatedEmpreendimentosRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/corretores': {
      id: '/_authenticated/corretores'
      path: '/corretores'
      fullPath: '/corretores'
      preLoaderRoute: typeof AuthenticatedCorretoresRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/comissoes': {
      id: '/_authenticated/comissoes'
      path: '/comissoes'
      fullPath: '/comissoes'
      preLoaderRoute: typeof AuthenticatedComissoesRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/aprovacoes': {
      id: '/_authenticated/aprovacoes'
      path: '/aprovacoes'
      fullPath: '/aprovacoes'
      preLoaderRoute: typeof AuthenticatedAprovacoesRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/agendamentos': {
      id: '/_authenticated/agendamentos'
      path: '/agendamentos'
      fullPath: '/agendamentos'
      preLoaderRoute: typeof AuthenticatedAgendamentosRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin/usuarios': {
      id: '/_authenticated/admin/usuarios'
      path: '/admin/usuarios'
      fullPath: '/admin/usuarios'
      preLoaderRoute: typeof AuthenticatedAdminUsuariosRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin/integracao': {
      id: '/_authenticated/admin/integracao'
      path: '/admin/integracao'
      fullPath: '/admin/integracao'
      preLoaderRoute: typeof AuthenticatedAdminIntegracaoRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/api/public/hooks/cleanup-nf-drive': {
      id: '/api/public/hooks/cleanup-nf-drive'
      path: '/api/public/hooks/cleanup-nf-drive'
      fullPath: '/api/public/hooks/cleanup-nf-drive'
      preLoaderRoute: typeof ApiPublicHooksCleanupNfDriveRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedRouteChildren {
  AuthenticatedAgendamentosRoute: typeof AuthenticatedAgendamentosRoute
  AuthenticatedAprovacoesRoute: typeof AuthenticatedAprovacoesRoute
  AuthenticatedComissoesRoute: typeof AuthenticatedComissoesRoute
  AuthenticatedCorretoresRoute: typeof AuthenticatedCorretoresRoute
  AuthenticatedEmpreendimentosRoute: typeof AuthenticatedEmpreendimentosRoute
  AuthenticatedFinanceiroRoute: typeof AuthenticatedFinanceiroRoute
  AuthenticatedGerentesRoute: typeof AuthenticatedGerentesRoute
  AuthenticatedInsightsRoute: typeof AuthenticatedInsightsRoute
  AuthenticatedVendasRoute: typeof AuthenticatedVendasRoute
  AuthenticatedIndexRoute: typeof AuthenticatedIndexRoute
  AuthenticatedAdminIntegracaoRoute: typeof AuthenticatedAdminIntegracaoRoute
  AuthenticatedAdminUsuariosRoute: typeof AuthenticatedAdminUsuariosRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedAgendamentosRoute: AuthenticatedAgendamentosRoute,
  AuthenticatedAprovacoesRoute: AuthenticatedAprovacoesRoute,
  AuthenticatedComissoesRoute: AuthenticatedComissoesRoute,
  AuthenticatedCorretoresRoute: AuthenticatedCorretoresRoute,
  AuthenticatedEmpreendimentosRoute: AuthenticatedEmpreendimentosRoute,
  AuthenticatedFinanceiroRoute: AuthenticatedFinanceiroRoute,
  AuthenticatedGerentesRoute: AuthenticatedGerentesRoute,
  AuthenticatedInsightsRoute: AuthenticatedInsightsRoute,
  AuthenticatedVendasRoute: AuthenticatedVendasRoute,
  AuthenticatedIndexRoute: AuthenticatedIndexRoute,
  AuthenticatedAdminIntegracaoRoute: AuthenticatedAdminIntegracaoRoute,
  AuthenticatedAdminUsuariosRoute: AuthenticatedAdminUsuariosRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  LoginRoute: LoginRoute,
  ApiPublicHooksCleanupNfDriveRoute: ApiPublicHooksCleanupNfDriveRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
